on:
  push:
    tags:
      - 'v*.*.*-rc-*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.4.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Container Image Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solusidatapintar/gatus
          tags: |
            type=semver,pattern={{raw}}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Container Image Build
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set Up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Set Up Certificate
        uses: azure/k8s-deploy@v1
        with:
          namespace: istio-system
          manifests: |
            k8s/certificate.yaml
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: prometheus
          manifests: |
            k8s/gateway.yaml
            k8s/virtualservice.yaml
            k8s/deployment.yaml
          images: |
            ghcr.io/solusidatapintar/gatus:${{ github.ref_name }}
